### ISSUE TITLE
Using Math.Net to solve linear equation in Grasshopper

### ISSUE THREAD

**Issue by yijiangh** [pilcru/wiki#1]
It could be useful to add this reference in your wiki:

[Using Math.Net Numerics in GHpython](http://www.grasshopper3d.com/profiles/blogs/using-math-net-numerics-in-ghpython)

**Comment by pilcru** [comment]
That's a great idea! Can you do it on the digital structures wiki
https://github.mit.edu/digitalstructures/wiki/? I'll merge all of that
someday, right now this wiki is only used for stuff that we send to the
students, since not all of them can access the MIT github.

You could add a new page, and reference it in my page about numpy. Make
sure you write a self-contained thing (links to the GH forum can go down),
and maybe show how to change your python path from the _EditPythonScript
window options in Rhino, rather than using a full path to your desktop
every time you want to run this in GH.

2016-11-12 21:17 GMT-05:00 Yijiang Huang notifications@github.com:
